# Use new container infrastructure to enable caching
sudo: false

language: ruby

# Caching so the next build will be fast too.
cache:
  bundler: true
  directories:
  - $HOME/.stack
  - $HOME/.agda
  - $HOME/.local
  - $HOME/agda-stdlib-master

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev
      - libicu-dev

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
# Download and install agda, agda-stdlib, and agda2html
- make setup

script:
- make

before_deploy:
- rm -rf .bundle
- rm -rf vendor
- make clean

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
