title: Agda Software Foundations
author: Pepijn Kokke
email: pepijn.kokke@gmail.com
description: > 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/sf"
url: "https://pepijnkokke.github.io"
github_username: pepijnkokke 
disqus:
  shortname: pepijnkokke

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - src/
  - Gemfile
  - Gemfile.lock
