name: 'Setup HTMLProofer'
description: 'Setup HTMLProofer'
runs:
  using: "composite"
  steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          # use .ruby-version
          bundler-cache: true
