name: 'Setup Python'
description: 'Setup Python'
runs:
  using: "composite"
  steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version-file: .python-version
          cache: 'pip'
          cache-dependency-path: requirements-dev.txt

      - name: Setup Python dependencies
        run: pip install -r requirements-dev.txt
        shell: pwsh

      - name: Get path to pipx virtual environment cache
        run: |
          $PIPX_VENV_CACHEDIR = pipx environment --value=PIPX_VENV_CACHEDIR | Out-String
          Echo "PIPX_VENV_CACHEDIR=${PIPX_VENV_CACHEDIR}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh

      - name: Cache pipx virtual environments
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.PIPX_VENV_CACHEDIR }}
          key: pipx-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements-dev.txt') }}
