name: Build

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - synchronize

env:
  CABAL_ARGS: "--project-file=cabal.project.ci"
  RECOMMENDED_OS: "Linux"
  RECOMMENDED_GHC_VERSION: "8.10.7"

defaults:
  run:
    shell: pwsh

jobs:

  ################################################################################
  # Build:
  ################################################################################
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc-version: ["8.10.7", "9.2.3"]
        include:
          - experimental: false

    name: Build on ${{ matrix.os }} with GHC ${{ matrix.ghc-version }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      # Setup

      - name: Setup Haskell
        uses: ./.github/actions/setup-haskell
        with:
          ghc-version: ${{ matrix.ghc-version }}
          cabal-project-freeze-file: cabal.project.ci.freeze

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Setup Python
        uses: ./.github/actions/setup-python

      - name: Setup Ruby
        uses: ./.github/actions/setup-ruby
        if: runner.os == 'Linux' || runner.os == 'macOS'

      - name: Setup EPUBCheck
        uses: ./.github/actions/setup-epubcheck
        id: setup-epubcheck
        with:
          epubcheck-version: "4.2.6"

      - name: Set version environment variables
        run: pipx run bumpver show --no-fetch --env | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      # Build

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: _cache
          key: build-${{ runner.os }}

      - name: Build artifact
        run: make build

      # Test

      - name: Test with HTML-validate
        run: make test-html-validate

      - name: Test with HTMLProofer
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: make test-html-proofer
        env:
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true

      - name: Test with EPUBCheck
        run: make test-epubcheck
        env:
          EPUBCHECK: "java -jar ${{ steps.setup-epubcheck.outputs.epubcheck-jar-path }}"

      # Upload artifact

      - name: Upload artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: Website HEAD ${{ runner.os }} GHC-${{ matrix.ghc-version }}
          path: _site
          if-no-files-found: error

      - name: Upload artifact for pull request
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: Website PR-${{ github.event.pull_request.number }} ${{ runner.os }} GHC-${{ matrix.ghc-version }}
          path: _site
          if-no-files-found: error

  ################################################################################
  # Deploy: On successful build, deploy all versions of PLFA to GitHub Pages
  ################################################################################
  deploy:
    name: Deploy
    concurrency: ci-${{ github.ref }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: github.event_name == 'push'
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      # Deploy: Prepare HEAD

      - name: Download latest artifact
        if: github.event_name == 'push'
        uses: actions/download-artifact@v3
        with:
          name: Website HEAD ${{ env.RECOMMENDED_OS }} GHC-${{ env.RECOMMENDED_GHC_VERSION }}
          path: site

      # Deploy: Prepare v19.08

      - name: Cache v19.08
        if: github.event_name == 'push'
        uses: actions/cache@v3
        id: cache-v19_08
        with:
          path: ${{ github.workspace }}/v19.08.zip
          key: version-v19_08

      - name: Download v19.08
        if: github.event_name == 'push' && steps.cache-v19_08.outputs.cache-hit != 'true'
        run: Invoke-WebRequest -Uri "https://github.com/plfa/plfa.github.io/releases/download/v19.08/Website.zip" -OutFile "${{ github.workspace }}/v19.08.zip"

      - name: Deploy v19.08
        if: github.event_name == 'push'
        run: Expand-Archive "${{ github.workspace }}/v19.08.zip" -DestinationPath "site/19.08"

      # Deploy: Prepare v20.07

      - name: Cache v20.07
        if: github.event_name == 'push'
        uses: actions/cache@v3
        id: cache-v20_07
        with:
          path: ${{ github.workspace }}/v20.07.zip
          key: version-v20_07

      - name: Download v20.07
        if: github.event_name == 'push' && steps.cache-v20_07.outputs.cache-hit != 'true'
        run: Invoke-WebRequest -Uri "https://github.com/plfa/plfa.github.io/releases/download/v20.07/Website.zip" -OutFile "${{ github.workspace }}/v20.07.zip"

      - name: Deploy v20.07
        if: github.event_name == 'push'
        run: Expand-Archive "${{ github.workspace }}/v20.07.zip" -DestinationPath "site/20.07"

      # Deploy: Publish to GitHub Pages

      - name: Deploy artifact
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: web
          folder: site

  ################################################################################
  # Release: On tag, publish the HEAD version of the website as a GitHub Release
  ################################################################################
  release:
    name: Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Download artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/download-artifact@v3
        with:
          name: HEAD
          path: site

      - name: Build release asset
        if: startsWith(github.ref, 'refs/tags/v')
        run: Compress-Archive -Path "site/*" Job-DestinationPath Website.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: Website.zip
          fail_on_unmatched_files: true
