on: [push, pull_request]

name: Build

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest]
        ghc: ['8.10.5']
        agda: ['2.6.1.3']

    steps:


    # Checkout

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Update stack.yaml
      run: |
        stack config set system-ghc true
        stack config set install-ghc false


    # Setup & Cache Haskell

    - name: Cache Haskell
      uses: actions/cache@v2
      id: cache-haskell
      with:
        path: |
          ~/.cabal
          ~/.ghc
          ~/.ghcup
          ~/.local
          ~/.stack
          $GITHUB_WORKSPACE/.stack-work
        key: ${{ matrix.os }}-ghc-${{ matrix.ghc }}

    - name: Setup Haskell
      if: steps.cache-haskell.outputs.cache-hit != 'true'
      uses: haskell/actions/setup@v1
      with:
        enable-stack: true
        ghc-version: ${{ matrix.ghc }}
        cabal-version: 'latest'
        stack-version: 'latest'


    # Setup & Cache HTMLProofer

    - name: Get Gem Installation Directory
      id: get-gemdir
      shell: bash

    - name: Get Ruby Configuration
      id: get-ruby-config
      run: |
        echo "::set-output name=ruby-version::$(ruby -e 'puts RUBY_VERSION')"
        echo "::set-output name=gem-version::$(gem --version)"
        echo "::set-output name=gem-directory::$(gem env gemdir)"
      shell: bash

    - name: Setup HTMLProofer
      if: steps.cache-htmlproofer.outputs.cache-hit != 'true'
      run: sudo gem install html-proofer

    - name: Cache HTMLProofer
      uses: actions/cache@v2
      id: cache-htmlproofer
      with:
        path: |
          ${{ steps.get-ruby-config.outputs.gem-directory }}
        key: ${{ matrix.os }}-ruby-${{ steps.get-ruby-config.outputs.ruby-version }}-gem-${{ steps.get-ruby-config.outputs.gem-version }}


    # Build & Test Website

    - name: Build Website
      run: make build

    - name: Test Website
      run: make test
