on: [push, pull_request]

name: Build

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest]
        ghc: ['8.10.5']
        agda: ['2.6.1.3']

    steps:


    # Checkout

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Update stack.yaml
      run: |
        stack config set system-ghc true
        stack config set install-ghc false
      shell: bash


    # Setup & Cache Haskell

    - name: Setup Haskell
      if: steps.cache-haskell.outputs.cache-hit != 'true'
      uses: haskell/actions/setup@v1
      with:
        enable-stack: true
        ghc-version: ${{ matrix.ghc }}
        cabal-version: 'latest'
        stack-version: 'latest'


    # Setup & Cache HTMLProofer

    - name: Get Ruby Info
      id: ruby-info
      run: |
        echo "::set-output name=ruby::$(ruby -e 'puts RUBY_VERSION')"
        echo "::set-output name=gem::$(gem --version)"
        echo "::set-output name=gemdir::$(gem env gemdir)"
      shell: bash

    - name: Setup HTMLProofer
      if: steps.cache-htmlproofer.outputs.cache-hit != 'true'
      run: sudo gem install html-proofer
      shell: bash

    - name: Cache HTMLProofer
      uses: actions/cache@v2
      id: cache-htmlproofer
      with:
        path: |
          ${{ steps.ruby-info.outputs.gemdir }}
        key: ${{ matrix.os }}-ruby-${{ steps.ruby-info.outputs.ruby }}-gem-${{ steps.ruby-info.outputs.gem }}



    # Setup & Cache site builder

    - name: Cache Site Builder
      uses: actions/cache@v2
      id: cache-site-builder
      with:
        path: |
          $GITHUB_WORKSPACE/.stack-work
        key: ${{ matrix.os }}-ghc-${{ matrix.ghc }}-agda-${{ matrix.agda }}

    - name: Build Site Builder
      if: steps.cache-site-builder.outputs.cache-hit != 'true'
      run: make build-deps
      shell: bash


    # Build & Test Website

    - name: Build Website
      run: make build
      shell: bash

    - name: Test Website
      run: make test
      shell: bash
