on: [push, pull_request]

name: Build

jobs:
  build:
    runs-on: macOS-latest

    strategy:
      matrix:
        ghc: ['8.10.5']

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Get Gem Installation Directory
      id: get-gemdir
      run: |
        echo "::set-output name=gemdir::$(gem env gemdir)"
      shell: bash

    - name: Get Agda version
      id: get-agda-version
      run: |
        echo "::set-output name=agda-version::$(cat plfa.cabal | sed -n -e 's/^.*Agda\s*==\s*\(\S*\)\s*/\1/p')"
      shell: bash

    - uses: actions/cache@v2
      name: Cache files
      id: cache
      with:
        path: |
          ~/.cabal
          ~/.ghc
          ~/.ghcup
          ~/.local
          ~/.stack
          ${{ steps.get-gemdir.outputs.gemdir }}
          $GITHUB_WORKSPACE/.stack-work
          $GITHUB_WORKSPACE/_build
          $GITHUB_WORKSPACE/_cache
          $GITHUB_WORKSPACE/_site
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ steps.get-agda-version.outputs.agda-version }}

    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
        stack-version: 'latest'

    - name: Setup HTMLProofer
      run: sudo gem install html-proofer

    - name: Build website
      run: |
        STACK="stack --system-ghc --no-install-ghc" make build

    - name: Test website
      run: |
        STACK="stack --system-ghc --no-install-ghc" make test
