name: Build & Test

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - synchronize

env:
  CABAL_ARGS: "--project-file=cabal.project.ci"
  NOKOGIRI_USE_SYSTEM_LIBRARIES: true

defaults:
  run:
    shell: pwsh

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc-version: ["8.10.7", "9.2.3"]
        include:
          - experimental: false

    name: Build on ${{ matrix.os }} with GHC-${{ matrix.ghc-version }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup Haskell
        uses: ./.github/actions/setup-haskell
        with:
          ghc-version: ${{ matrix.ghc-version }}
          cabal-project-freeze-file: cabal.project.ci.freeze

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: _cache
          key: build-${{ runner.os }}

      - name: Build website
        run: make build

      - name: Test with HTML-validate
        run: make test-html-validate

      - name: Setup bundler
        if: runner.os != 'Windows'
        uses: ./.github/actions/setup-bundler

      - name: Test with HTMLProofer
        if: runner.os != 'Windows'
        run: make test-html-proofer

      - name: Setup EPUBCheck
        uses: ./.github/actions/setup-epubcheck
        id: setup-epubcheck
        with:
          epubcheck-version: "4.2.6"

      - name: Test with EPUBCheck
        run: make test-epubcheck
        env:
          EPUBCHECK: "java -jar ${{ steps.setup-epubcheck.outputs.epubcheck-jar-path }}"

      - name: Upload artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: Website HEAD ${{ runner.os }} GHC-${{ matrix.ghc-version }}
          path: _site
          if-no-files-found: error

      - name: Upload artifact for pull request
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: Website PR-${{ github.event.pull_request.number }} ${{ runner.os }} GHC-${{ matrix.ghc-version }}
          path: _site
          if-no-files-found: error

  publish:
    name: Publish to GitHub Pages
    needs: [build]
    if: github.event_name == 'push'
    uses: ./.github/workflows/publish.yml
    with:
      artifact-name: Website HEAD Linux GHC-8.10.7

  release:
    name: Publish to GitHub Releases
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/release.yml
