on: [push, pull_request]

name: Build

jobs:
  build:
    runs-on: macOS-latest

    env:
      # Use the GHC version installed by haskell/actions/setup
      #
      # NOTE: Makefile respects the STACK environment variable
      #
      STACK: stack --system-ghc --no-install-ghc

    strategy:
      matrix:
        ghc: ['8.10.5']
        agda: ['2.6.1.3']

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Get Gem Installation Directory
      id: get-gemdir
      run: echo "::set-output name=gemdir::$(gem env gemdir)"
      shell: bash

    - uses: actions/cache@v2
      name: Cache files
      id: cache
      with:
        path: |
          ~/.cabal
          ~/.ghc
          ~/.ghcup
          ~/.local
          ~/.stack
          ${{ steps.get-gemdir.outputs.gemdir }}
          $GITHUB_WORKSPACE/.stack-work
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.agda }}

    - name: Setup Haskell
      if: steps.cache.outputs.cache-hit != 'true'
      uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
        stack-version: 'latest'

    - name: Setup HTMLProofer
      if: steps.cache.outputs.cache-hit != 'true'
      run: sudo gem install html-proofer

    - name: Build website
      run: make build

    - name: Test website
      run: make test
