on: [push, pull_request]

name: Build

jobs:
  build:
    runs-on: macOS-latest

    strategy:
      matrix:
        ghc: ['8.10.5']
        agda: ['2.6.1.3']

    steps:


    # Checkout

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Update stack.yaml
      run: |
        stack config set system-ghc true
        stack config set install-ghc false


    # Setup & Cache Haskell

    - name: Cache Haskell
      uses: actions/cache@v2
      id: cache-haskell
      with:
        path: |
          ~/.cabal
          ~/.ghc
          ~/.ghcup
          ~/.local
          ~/.stack
          $GITHUB_WORKSPACE/.stack-work
        key: ${{ runner.os }}-ghc-${{ matrix.ghc }}

    - name: Setup Haskell
      if: steps.cache-haskell.outputs.cache-hit != 'true'
      uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true


    # Setup & Cache HTMLProofer

    - name: Get Gem Installation Directory
      id: get-gemdir
      run: echo "::set-output name=gemdir::$(gem env gemdir)"
      shell: bash

    - name: Get Ruby Version
      id: get-ruby-version
      run: echo "::set-output name=ruby-version::$(ruby -e 'puts RUBY_VERSION')"
      shell: bash

    - name: Setup HTMLProofer
      if: steps.cache-htmlproofer.outputs.cache-hit != 'true'
      run: sudo gem install html-proofer

    - name: Cache HTMLProofer
      uses: actions/cache@v2
      id: cache-htmlproofer
      with:
        path: |
          ${{ steps.get-gemdir.outputs.gemdir }}


    # Build & Test Website

    - name: Build Website
      run: make build

    - name: Test Website
      run: make test
