name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - synchronize

env:
  CABAL_ARGS: "--project-file=cabal.project.ci"
  HTML_PROOFER: "bundle exec htmlproofer"
  NOKOGIRI_USE_SYSTEM_LIBRARIES: true

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ghc-version: ["8.10.7"]
        cabal-version: ["3.6"]
        node-version: ["16"]
        include:
          - experimental: false
    
        
    name: Build (${{ matrix.os }} with GHC ${{ matrix.ghc-version }})
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup EPUBCheck (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y epubcheck

      - name: Setup EPUBCheck (macOS)
        if: runner.os == 'macOS'
        run: brew install epubcheck

      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc-version }}
          cabal-version: ${{ matrix.cabal-version }}

      - name: Cabal freeze
        run: |
          cabal v2-update
          cabal v2-freeze $CABAL_ARGS --enable-tests --enable-benchmarks

      - name: Cache Haskell
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            dist-newstyle
          key: haskell-${{ matrix.os }}-${{ matrix.ghc-version }}-${{ hashFiles('cabal.project.ci.freeze') }}
          restore-keys: |
            haskell-${{ matrix.os }}-${{ matrix.ghc-version }}-
            ${{ matrix.os }}-GHC-${{ matrix.ghc-version }}-${{ hashFiles('cabal.project.ci.freeze') }}
            ${{ matrix.os }}-GHC-${{ matrix.ghc-version }}-
          
      - name: Cache Shake Build
        uses: actions/cache@v3
        with:
          path: |
            _cache
            _site
          key: build-${{ matrix.os }}
          restore-keys: |
            ${{ matrix.os }}-output

      - name: Build website
        run: make build

      - name: Test with html-validate
        run: make test-html-validate

      - name: Test with HTMLProofer
        run: make test-html-proofer

      - name: Test with EPUBCheck
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: make test-epubcheck

      - name: Upload artifact (Push)
        if: runner.os == 'Linux' && github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: latest
          path: _site
          if-no-files-found: error
          
      - name: Upload artifact (Pull Request)
        if: runner.os == 'Linux' && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: pull-request-${{ github.event.pull_request.number }} 
          path: _site
          if-no-files-found: error
          
  deploy:
    name: Deploy
    concurrency: ci-${{ github.ref }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: github.event_name == 'push'
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Download Artifact
        if: github.event_name == 'push'
        uses: actions/download-artifact@v3
        with:
          name: latest
          path: latest

      - name: Deploy Artifact
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: web
          folder: latest
    


        
