name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - synchronize

env:
  CABAL_ARGS: "--project-file=cabal.project.ci"
  NOKOGIRI_USE_SYSTEM_LIBRARIES: true # Use fast system libraries for html-proofer.
  npm_config_yes: true # Don't ask for confirmation before installing packages.

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc-version: ["8.10.7"]
        cabal-version: ["3.6"]
        node-version: ["16"]
        include:
          # Experimental builds.
          - experimental: false
          - os: windows-latest
            experimental: true
          # Default shells.
          - shell: bash
          - os: windows-latest
            shell: msys {0}
          # Pretty OS names.
          - os: ubuntu-latest
            os-pretty: Linux
          - os: macOS-latest
            os-pretty: macOS
          - os: windows-latest
            os-pretty: Windows

    name: Build on ${{ matrix.os-pretty }} with GHC ${{ matrix.ghc-version }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
        
      - name: Setup MSYS (Windows)
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git
            pkg-config
            icu

      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc-version }}
          cabal-version: ${{ matrix.cabal-version }}

      - name: Cabal freeze
        run: |
          cabal v2-update
          cabal v2-freeze $CABAL_ARGS --enable-tests --enable-benchmarks

      - name: Cache Haskell
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            dist-newstyle
          key: haskell-${{ runner.os }}-${{ matrix.ghc-version }}-${{ hashFiles('cabal.project.ci.freeze') }}
          restore-keys: |
            haskell-${{ runner.os }}-${{ matrix.ghc-version }}-
            haskell-${{ matrix.os }}-${{ matrix.ghc-version }}-
          
      - name: Cache Shake build
        uses: actions/cache@v3
        with:
          path: |
            _cache
            _site
          key: build-${{ runner.os }}
          restore-keys: |
            build-${{ matrix.os }}
  
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
    
      - name: Build artifact
        run: make build

      - name: Test with HTML-validate
        run: make test-html-validate

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
  
      - name: Test with HTMLProofer
        run: make test-html-proofer

      - name: Setup EPUBCheck (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y epubcheck

      - name: Setup EPUBCheck (macOS)
        if: runner.os == 'macOS'
        run: brew install epubcheck
        
      - name: Test with EPUBCheck
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: make test-epubcheck

      - name: Upload artifact
        if: runner.os == 'Linux' && github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: latest
          path: _site
          if-no-files-found: error
          
      - name: Upload artifact for pull request
        if: runner.os == 'Linux' && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: pull-request-${{ github.event.pull_request.number }} 
          path: _site
          if-no-files-found: error
          
  deploy:
    name: Deploy
    concurrency: ci-${{ github.ref }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: github.event_name == 'push'
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Download artifact
        if: github.event_name == 'push'
        uses: actions/download-artifact@v3
        with:
          name: latest
          path: latest

      - name: Deploy artifact
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: web
          folder: latest
    


        
