name: pages-build-compose

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string

jobs:
  pages-build-compose:
    name: Compose versions
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      # Download latest & releases

      - name: Download latest artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: site

      - uses: ./.github/actions/download-plfa-release
        with:
          plfa-version: v19.08
          path: site

      - uses: ./.github/actions/download-plfa-release
        with:
          plfa-version: v20.07
          path: site

      # Publish to GitHub Pages

      - name: Publish artifact
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: web
          folder: site
