name: pages-build-versions

on: [workflow_call]

env:
  RECOMMENDED_OS: "Linux"
  RECOMMENDED_GHC_VERSION: "8.10.7"

jobs:
  pages-build-versions:
    name: Compose versions & publish
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      # Download latest & releases

      - name: Download latest artifact
        uses: actions/download-artifact@v3
        with:
          name: Website HEAD ${{ env.RECOMMENDED_OS }} GHC-${{ env.RECOMMENDED_GHC_VERSION }}
          path: site

      - uses: ./.github/actions/download-plfa-release
        with:
          plfa-version: v19.08
          path: site

      - uses: ./.github/actions/download-plfa-release
        with:
          plfa-version: v20.07
          path: site

      # Publish to GitHub Pages

      - name: Publish artifact
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: web
          folder: site
